"use strict";
exports.__esModule = true;
var command_1 = require("./command");
var Fan_1 = require("./Fan");
var GarageDoor_1 = require("./GarageDoor");
var Light_1 = require("./Light");
var remote_1 = require("./remote");
var Stereo_1 = require("./Stereo");
function run() {
    var rc = new remote_1.Remote();
    var livingLight = new Light_1.Light();
    var livingRoomOn = new command_1.LightOnCommand(livingLight);
    var livingRoomOff = new command_1.LightOffCommand(livingLight);
    var kitchenLight = new Light_1.Light();
    var kitchenOn = new command_1.LightOnCommand(kitchenLight);
    var kitchenOff = new command_1.LightOffCommand(kitchenLight);
    var fan = new Fan_1.Fan();
    var lvngFanOn = new command_1.FanOnCommand(fan);
    var lvngFanOff = new command_1.FanOffCommand(fan);
    var gd = new GarageDoor_1.GarageDoor();
    var doorOpen = new command_1.GarageDoorOpenCommand(gd);
    var doorClose = new command_1.GarageDoorCloseCommand(gd);
    var stro = new Stereo_1.Stereo();
    var stroOff = new command_1.StereoOffCommand(stro);
    var stroOn = new command_1.StereoOnCommand(stro);
    var comArray = [livingRoomOn, lvngFanOn, stroOn];
    var offArray = [livingRoomOff, lvngFanOff, stroOff];
    var mcCmd = new command_1.MacroCommand(comArray);
    var offComd = new command_1.MacroCommand(offArray);
    rc.setCommand(0, livingRoomOn, livingRoomOff);
    rc.setCommand(1, kitchenOn, kitchenOff);
    rc.setCommand(2, lvngFanOn, lvngFanOff);
    rc.setCommand(3, doorOpen, doorClose);
    rc.setCommand(4, stroOn, stroOff);
    rc.setCommand(5, mcCmd, offComd);
    rc.onButton(0);
    rc.onButton(3);
    rc.onButton(4);
    rc.onButton(1);
    rc.onButton(2);
    rc.undoButton();
    rc.offButton(3);
    rc.undoButton();
    rc.offButton(2);
    rc.offButton(0);
    rc.offButton(4);
    rc.undoButton();
    rc.offButton(1);
    console.log('MACRO COMMAND');
    rc.onButton(5);
    rc.offButton(5);
    console.log('UNDO OPERATION');
    rc.undoButton();
}
run();
